export declare const URL_ABOUT_ESMIRA_SOURCE = "https://raw.githubusercontent.com/KL-Psychological-Methodology/ESMira/main/about/";
export declare const URL_ABOUT_ESMIRA_STRUCTURE_JSON: string;
export declare const URL_ABOUT_ESMIRA_PUBLICATIONS_JSON: string;
export declare const URL_ABOUT_ESMIRA_JSON: string;
export declare const URL_RELEASES_LIST = "https://api.github.com/repos/KL-Psychological-Methodology/ESMira-web/releases?per_page=50";
export declare const URL_DEV_SERVER = "esmira.kl.ac.at";
export declare const URL_BLOG_RSS = "https://kl-psychological-methodology.github.io/ESMira/feed.xml";
export declare const FILE_CHECK_HTACCESS = "api/checkHtaccess/check.php";
export declare const FILE_ADMIN = "api/admin.php";
export declare const FILE_RESPONSES: string;
export declare const FILE_CREATE_MEDIA: string;
export declare const FILE_MEDIA: string;
export declare const FILE_IMAGE: string;
export declare const FILE_AUDIO: string;
export declare const FILE_SAVE_ACCESS = "api/access.php";
export declare const FILE_SETTINGS = "api/settings.php?lang=%1&type=%2";
export declare const FILE_APP_INSTALL_INSTRUCTIONS = "api/app_install_instructions.php?id=%d1&access_key=%s1&lang=%s2";
export declare const FILE_GET_QUESTIONNAIRE = "api/questionnaire.php?id=%d1&qid=%d2&access_key=%s1&lang=%s2&%s3";
export declare const FILE_SERVER_STATISTICS = "api/server_statistics.php";
export declare const FILE_STATISTICS = "api/statistics.php?id=%d&access_key=%s";
export declare const FILE_STUDIES = "api/studies.php";
