export declare class MerlinToken {
    type: MerlinTokenType;
    lexeme: string;
    line: number;
    constructor(type: MerlinTokenType, lexeme: string, line: number);
}
export declare enum MerlinTokenType {
    LEFT_PAREN = 0,
    RIGHT_PAREN = 1,
    LEFT_BRACE = 2,
    RIGHT_BRACE = 3,
    LEFT_BRACKET = 4,
    RIGHT_BRACKET = 5,
    COMMA = 6,
    COLON = 7,
    SEMICOLON = 8,
    DOT = 9,
    MINUS = 10,
    PLUS = 11,
    SLASH = 12,
    STAR = 13,
    DOT_DOT = 14,
    EXCLAMATION = 15,
    EXCLAMATION_EQUAL = 16,
    EQUAL = 17,
    EQUAL_EQUAL = 18,
    GREATER = 19,
    GREATER_EQUAL = 20,
    LESS = 21,
    LESS_EQUAL = 22,
    GREATER_GREATER = 23,
    IDENTIFIER = 24,
    STRING = 25,
    NUMBER = 26,
    AND = 27,
    ELSE = 28,
    ELIF = 29,
    FALSE = 30,
    FUNCTION = 31,
    FOR = 32,
    IF = 33,
    IN = 34,
    INIT = 35,
    NONE = 36,
    OBJECT = 37,
    OR = 38,
    RETURN = 39,
    TRUE = 40,
    WHILE = 41,
    EOF = 42
}
