---
title: "Sociology of Culture & Cognition"
author: "Luca Carbone"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: default
  html_document: default
urlcolor: blue
---

The scaffolds of contemporary cognitive sociology can be found in [DiMaggio (1997)](https://www-annualreviews-org.kuleuven.ezproxy.kuleuven.be/doi/10.1146/annurev.soc.23.1.263) and [Zerubavel (1997)](https://www.hup.harvard.edu/catalog.php?isbn=9780674813908). The cultural perspective promoted by [Ann Swidler (1986)](https://www-jstor-org.kuleuven.ezproxy.kuleuven.be/stable/2095521?sid=primo&origin=crossref&seq=1#metadata_info_tab_contents), in which culture was not seen as aggregate of beliefs, values, and attitudes, but more as a toolkit that enables or constraints action, prompted new ways to theorize about social action and the interplay between culture and cognitive processes.
The following, is a list of important papers in the field, selected by topic. One of the most updated and comprehensive sources of the field is offered by the [Oxford Handbook of Cognitive Sociology (2019, eds. Brekhus & Ignatow)](https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190273385.001.0001/oxfordhb-9780190273385). Several of the entrances below come from this source.

### General overview of the field
* Brekhus, Wayne & Ignatow, Gabe. 2019. “Cognitive Sociology and the Cultural Mind: debates, directions, and challenges.” Eds. W. Brekhus and G. Ignatow, Oxford Handbook of Cognitive Sociology.[link](https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190273385.001.0001/oxfordhb-9780190273385-e-1);
* Brekhus, Wayne H. 2015. *Culture and Cognition: Patterns in the Social Construction of Reality.* Cambridge UK/Malden, MA: Polity.[link](https://www.wiley.com/en-be/Culture+and+Cognition%3A+Patterns+in+the+Social+Construction+of+Reality-p-9780745671765);
* Strydom, P. (2007). Introduction: A Cartography of Contemporary Cognitive Social Theory. European Journal of Social Theory, 10(3), 339–356.[link](https://journals.sagepub.com/doi/abs/10.1177/1368431007080699);
* Martin, John Levi. 2010. “Life’s a Beach but You’re an Ant, and Other Unwelcome News for the Sociology of Culture.” Poetics 38(2):229–44.[link](https://www.sciencedirect.com/science/article/abs/pii/S0304422X09000618#vt1).

### Automatic VS Deliberative cognition: dual-process models
* Vaisey, Stephen. 2009. “Motivation and Justification: A Dual-Process Model of Culture in Action.” American Journal of Sociology 114(6):1675–1715.[link](https://www.journals.uchicago.edu/doi/abs/10.1086/597179);
* Shepherd, Hana. 2011. “The Cultural Context of Cognition: What the Implicit Association Test Tells Us About How Culture Works.” Sociological Forum 26: 121-143. [link](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1573-7861.2010.01227.x);
* Lizardo, Omar, Robert Mowry, Brandon Sepulvado, Dustin S. Stoltz, Marshall A. Taylor, Justin Van Ness and Michael Lee Wood. 2016. “What are dual process models? Implications for cultural analysis in sociology.” Sociological Theory 34(4): 287-310.[link](https://journals.sagepub.com/doi/10.1177/0735275116675900);
* Strandel, Jacob. 2019. “Bridging the Vocabularies of Dual-Process Models of Culture and Cognition” Eds. W. Brekhus and G. Ignatow, Oxford Handbook of Cognitive Sociology.[link](https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190273385.001.0001/oxfordhb-9780190273385-e-11);
* Vaisey, Stephen and Frye, Margaret. 2019. “The Old One-Two: preserving analytical dualism in cognitive sociology” Eds. W. Brekhus and G. Ignatow, Oxford Handbook of Cognitive Sociology.[link](https://www-oxfordhandbooks-com.kuleuven.ezproxy.kuleuven.be/view/10.1093/oxfordhb/9780190273385.001.0001/oxfordhb-9780190273385-e-6);
* Leschziner, Vanina. 2019. “Dual-Process Models in Sociology” Eds. W. Brekhus and G. Ignatow, Oxford Handbook of Cognitive Sociology.[link](https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190273385.001.0001/oxfordhb-9780190273385-e-10);
* Moore, Rick. 2017. “Fast or Slow: Sociological Implications of Measuring Dual-Process Cognition.” Sociological Science 4:196–223.[link](https://www.sociologicalscience.com/articles-v4-9-196/).

### Methodological perspectives
* Stephen Vaisey, Omar Lizardo, Can Cultural Worldviews Influence Network Composition?, Social Forces, Volume 88, Issue 4, June 2010, Pages 1595–1618.[link](https://academic.oup.com/sf/article-abstract/88/4/1595/1895191?redirectedFrom=fulltext);
* Boutyline, Andrei and Stephen Vaisey. 2017. "Belief Network Analysis: A Relational Approach to Understanding the Structure of Attitudes." American Journal of Sociology 122: 1371-1447.[link](https://www.journals.uchicago.edu/doi/10.1086/691274?mobileUi=0)
* Boutyline, Andrei. 2017. “Improving the Measurement of Shared Cultural Schemas with Correlational Class Analysis: Theory and Method.” Sociological Science 4:353–93.[link](https://www.sociologicalscience.com/articles-v4-15-353/);
* Miles, A., Charron-Chénier, R., & Schleifer, C. (2019). Measuring Automatic Cognition: Advancing Dual-Process Research in Sociology. American Sociological Review, 84(2), 308–333.[link](https://journals.sagepub.com/doi/abs/10.1177/0003122419832497#articleCitationDownloadContainer);
* Miles, Andrew. 2019. “An Assessment of Methods for Measuring Automatic Cognition” Eds. W. Brekhus and G. Ignatow, Oxford Handbook of Cognitive Sociology. [link](https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190273385.001.0001/oxfordhb-9780190273385-e-19);
* Hunzaker, M. B. Fallin and Lauren Valentino. 2019. “Mapping Cultural Schemas: From Theory to Method.” American Sociological Review 84(5):950–81.[link](https://journals.sagepub.com/doi/abs/10.1177/0003122419875638);
* Martin, John Levi.  2000.  “The Relation of Aggregate Statistics on Belief to Culture and Cognition.”  Poetics 28: 5-20.[link](https://www.sciencedirect.com/science/article/abs/pii/S0304422X00000103)
* Moore, Rick. 2017. “Fast or Slow: Sociological Implications of Measuring Dual-Process Cognition.” Sociological Science 4:196–223.[link](https://www.sociologicalscience.com/articles-v4-9-196/).

### Declarative and non-declarative culture
* Cerulo, Karen A. 2018. “Scents and Sensibility: Olfaction, Sense-making and Meaning Attribution.” American Sociological Review 83: 2: 361-389.[link](https://journals.sagepub.com/doi/10.1177/0003122418759679);
* Lizardo, Omar. 2017. "Improving Cultural Analysis Considering Personal Culture in its Declarative and Nondeclarative Modes." American Sociological Review 82(1):88-115.[link](https://journals.sagepub.com/doi/10.1177/0003122416675175).

### Cognitive apporaches to culture
* Lizardo, Omar and Michael Strand. 2010. “Skills, Toolkits, Contexts and Institutions: Clarifying the Relationship between Different Approaches to Cognition in Cultural Sociology.” Poetics 38(2):205–28.[link](https://www.sciencedirect.com/science/article/abs/pii/S0304422X09000606).

### Cultural approaches
* Vaisey, S. (2010). What People Want: Rethinking Poverty, Culture, and Educational Attainment. The ANNALS of the American Academy of Political and Social Science, 629(1), 75–101. [link](https://journals-sagepub-com.kuleuven.ezproxy.kuleuven.be/doi/abs/10.1177/0002716209357146);
* Santos, Henri et al. 2019. “Class, Cognition, and Cultural Change in Social Class” Eds. W. Brekhus and G. Ignatow, Oxford Handbook of Cognitive Sociology. [link](https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190273385.001.0001/oxfordhb-9780190273385-e-15).

### Bridging fields
* Lamont, Michèle, Laura Adler, Bo Yun Park, and Xin Xiang. 2017. “Bridging Cultural Sociology and Cognitive Psychology in Three Contemporary Research Programmes.” Nature Human Behaviour 1(12):866–72.[link](https://www.nature.com/articles/s41562-017-0242-y);
* Cerulo, Karen. 2010. "Mining the Intersections of Cognitive Sociology and Neurosceince." Poetics 38: 2: 115-132.[link](https://www.sciencedirect.com/science/article/abs/pii/S0304422X0900062X).

### Additional resources
* [Omar Lizardo's syllabus](https://docs.google.com/document/d/e/2PACX-1vSfYxPJcm-gXaFIBLr0RHkpAuYcRMHxMpVkIOehoU_5eGYrHt_nMoU0qStJjrfWGXmU8UAlN-GLckYe/pub) for the course Culture and Cognition at Notre Dame (Spring 2017);
* [John Levi Martin's syllabus](http://home.uchicago.edu/~jlmartin/901%20syllabus.pdf) for the course Culture and Cognition at University of Wisconsin, Madison (Spring 2005);
* [Karen Cerulo's bibliographic material](http://www.sas.rutgers.edu/virtual/cultcog/bibliography_1.html)
* Omar Lizardo and Michael Strand (UCLA) have a blog called [CultureCog](https://culturecog.blog) in which they write posts about central concepts in this filed, such as that of habitus and embodiment. They adopt a Bourdieusian perspective, for which culture is not studied in its social representations (Durkheim) or interpersonal/micro situations (Goffman), but as incorporated in everyday practices (see, for example, [Dieter Vandebroeck's (2016)](https://www.routledge.com/Distinctions-in-the-Flesh-Social-Class-and-the-Embodiment-of-Inequality/Vandebroeck/p/book/9781138123557) book about how class divisions become inscribed in the body and how physical properties, in turn, contribute to naturalizing and legitimizing class divisions). The blog constitues a good companion to the papers to better grasp and reflect upon their main theoretical, methodological, and empirical findings.

