---
title: "CV"
author: "Luca Carbone"
email: luca.carbone@kuleuven.be
output:
  pdf_document:
    latex_engine: pdflatex
    template: ~/Dropbox/university/website/static/files/CV/svm-latex-cv.tex
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 12pt
geometry: margin=1in
jobtitle: KU Leuven, Department of Mass Communication
keywords: R Markdown, academic CV, template
linkcolor: blue
fontawesome: yes
phone: +32 16 37 24 05
address: Parkstraat 45 · 3000 Leuven · Belgium
urlcolor: blue
web: www.lucacarbone.com
---

# Education
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

*KU Leuven, BE* \hfill \begingroup\small 2020-2024\endgroup\
Ph.D. Social Sciences - ERC starting grant\
Promoter: Laura Vandenbosch\
PhD committee: Steven Eggermont, Giselinde Kuipers, Tom ter Bogt\
[Project website](http://www.projectmimic.eu)

*Tilburg University, NL* \hfill \begingroup\small 2017-2019\endgroup\
M.Sc. (Res.) Social Sciences\
Awarded best student, GPA 8.41/10, cum laude

*University of Trento, IT* \hfill \begingroup\small 2014-2017\endgroup\
B.A. Sociology\
GPA 28.74/30, 110 cum laude

# Research interests
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

**Cultural/cognitive sociology and inequalities**: cultural (re)production; socio-aesthetic hierarchies; success, meritocracy, individualism, and social status; boundary-making processes; public and personal forms of culture.\

**Media psychology**: media entertainment; resonance theory; media frames; cultivation theory.\

**Advanced quantitative research methods**: computational social science methods, including statistical inference in networks (ERGM), text as data (structural topic modeling); structural equation modeling; multilevel analysis; factor analysis and data reduction.

# Publications
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

## Peer-reviewed articles

__Carbone, L.__ & Vandenbosch, L. (2023). A Meta-Analysis of Studies Examining the Effect of Music on Beliefs *Communication Research*. [https://doi.org/10.1177/00936502231163633](https://doi.org/10.1177/00936502231163633)
\newline

Grusauskaite, K., __Carbone, L.__, Harambam, J., & Aupers, S. (2023). Debating (In) Echo Chambers: How People Read Conspiracy Theory Videos On YouTube *New Media & Society*. [https://doi.org/10.1177/14614448231162585](https://doi.org/10.1177/14614448231162585). Finalist in the ICA Popular Media & Culture division’s Top Paper Award in 2022 (out of 229 total papers).
\newline

Rosič J., Janicke-Bowles S.H., __Carbone, L.__, Lobe B., Vandenbosch L. (2022). Positive Digital Communication Among Youth: The Development and Validation of the Digital Flourishing Scale for Adolescents *Frontiers Digital Health*. [https://doi.org/10.3389/fdgth.2022.975557](https://doi.org/10.3389/fdgth.2022.975557).
\newline

__Carbone, L.__ (2022). Book Review: 'Getting Signed: Record Contracts, Musicians, and Power in Society.' *New Media & Society*. [https://doi.org/10.1177/14614448221101210](https://doi.org/10.1177/14614448221101210).
\newline

__Carbone, L.__ & Mijs, J. (2022). Sounds like meritocracy to my ears: Exploring the link between inequality in popular music and personal culture. *Information, Communication & Society*. [https://doi.org/10.1080/1369118X.2021.2020870](https://doi.org/10.1080/1369118X.2021.2020870). Pre-print available [here](https://t.co/znOwdcxRO2?amp=1). Data, syntax, appendix, and pre-registration available on [OSF](https://osf.io/5427t/). Trending paper in Communication and Sociology Altmetrics on 10th January 2022 [OOIR](https://t.co/6jLlFffvFT)
\newline

## Book Chapters

Kuipers, Giselinde, Brans, Luuc, __Carbone, Luca__: "The myth of trickle down. How fashions do (not) spread in European fashion magazines, and what this tells us about power and status in the global fashion system" (in publication)
\newline

__Carbone, Luca__ .2019. "Il mercato comunicativo su Twitter nelle europee 2019."" In: Valbruzzi, Marco (Ed.) *L’Italia sovranista e la sfida all’Europa. Le elezioni europee ed amministrative 2019* (56-63). Bologna: Istituto Carlo Cattaneo. DOI: 10.31484/2611-5778_41

__Carbone, Luca__ .2019. "Twitter come mercato comunicativo? Un’analisi sulle europee 2019." In: Valbruzzi, Marco (Ed.) *L’Italia sovranista e la sfida all’Europa. Le elezioni europee ed amministrative 2019* (65-73). Bologna: Istituto Carlo Cattaneo. DOI: 10.31484/2611-5778_41
\newline

## Work in progress

__Carbone, Luca__, Vandenbosch, Laura, & Song, Hyunjin (Yonsei University): "The Sound of Meritocracy: A Content Analysis of Meritocracy in Popular Music Lyrics Using a Semantic and Syntactic Framing Approach" (Under Review)
\newline

__Carbone, Luca__, Alvarez-Cueva, Priscila, & Vandenbosch, Laura: "“I know I'm a queen, but I don't need no crown”: Intersectional Representations of Social Status in Popular Music Lyrics" (Under review)
\newline

Pirrone, Davide, __Carbone, Luca__, van Oosten, Annemarie, & Vandenbosch, Laura: "From Affordance to Affair: Exploring the Relationships between Online Sexual Activities and Online Infidelity Behaviors" (Under review)
\newline

Rosič, Jasmina, __Carbone, Luca__, Vanden Abeele, Mariek, Lobe, Bojana, & Vandenbosch, Laura: "Measuring Adolescents’ Digital Well-Being in Everyday Life: The Perceived Digital Balance in Adolescence Scale" (Under review)
\newline

__Carbone, Luca__ & Vandenbosch, Laura: "Adolescents’ music identity in the streaming era" (Drafting)
\newline

__Carbone, Luca__, Klimmt, Christoph, Schaap, Julian, & Vandenbosch, Laura: "Resonant Mediated Experiences: Towards an Integrated Approach of Media-Psychological and Cultural Sociological Theories of Resonance" (Drafting)
\newline

__Carbone, Luca__, Klimmt, Christoph, & Vandenbosch, Laura: "The Development of Music-Consistent Beliefs through Identification and Similarity with Music Artists: A Biographic Resonance Account" (Drafting)
\newline

Vandenbosch, Laura, __Carbone, Luca__, Noon, Ed: "A Self-Determination Perspective on Adolescents’ Videogame Play, Need Satisfaction, and Self-Esteem" (Drafting)
\newline

__Carbone, Luca__, Mijs, Jonathan (Boston University, Erasmus University), Thijs van Dooremalen (KU Leuven) & Daedekindt, Stijn (Ghent University): "Leading or Trailing? Eurovision and the Resonant Duality of Mediated Mega Events" (Drafting)
\newline

## Other Publications

Brusco, Sandro; __Carbone, Luca__; Miglino, Enrico; Tazzioli, Agostino (2019, 30 May), Una semplice analisi econometrica del voto a Più Europa del 2019 (A simple econometric analysis of the 2019 vote to +Europe). Research report for NoiseFromAmerika. Available [here](http://noisefromamerika.org/articolo/semplice-analisi-econometrica-voto-piu-europa-2019?fbclid=IwAR12kLTGJAonRf3Ctb-HlXYBGAspUhOSclDpQCg-mis-mDzM9vY8kZU21v8)

__Carbone, Luca__ (2019, 6 February), Il Dibattito Online sull’Immigrazione in Italia (The Online Debate about Immigration in Italy). Research report for Istituto Carlo Cattaneo. Available [here](http://www.cattaneo.org/2019/02/06/il-dibattito-online-sullimmigrazione-in-italia/)

__Carbone, Luca__ (2018, 21 August), Sociology Journals and Network Proprieties of the St. Matthew Effect [blog post]. Available [here](https://economicsociology.org/2018/08/21/sociological-journals-and-network-proprieties-of-the-st-matthew-effect/)

# Awards & Funds
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

University of Chicago, scholarship & Dean’s fellowship ($31,500).
\hfill \begingroup\small 2019-2020 \endgroup\
*(declined due to insufficient financial resources to enroll in the program)*

Tilburg University, visiting fund at Exeter University (€1000).  \hfill \begingroup\small June-August 2018\endgroup

# Invited Talks
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

POP Talks (IASPM Benelux), Leuven \hfill \begingroup\small 2023\endgroup

# Conference Presentations
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

73rd conference of the International Communication Association (ICA), Toronto \hfill \begingroup\small 2023\endgroup

Etmaal van de Communicatiewetenschap 2023, Enschede. \hfill \begingroup\small 2023\endgroup

21st conference of the International Association for the Study of Popoular Music (IASPM), Daegu. \hfill \begingroup\small 2022\endgroup

Day of Sociology, Groningen \hfill \begingroup\small 2022\endgroup

72nd conference of the International Communication Association (ICA), Paris. \hfill \begingroup\small 2022\endgroup

Etmaal van de Communicatiewetenschap 2022, Brussels (online). \hfill \begingroup\small 2022\endgroup

Workshop PhD Media Psychology division of German Psychological Association Conference, Aachen. \hfill \begingroup\small 2021\endgroup

116th ASA Virtual Annual Meeting (American Sociological Association), Chicago (online). \hfill \begingroup\small 2021\endgroup

7th International Conference on Computational Social Science IC2S2, ETH Zürich (online). \hfill \begingroup\small 2021\endgroup

4th Joint Interdisciplinary Graduate Conference, Tilburg University (online). \hfill \begingroup\small 2021\endgroup

IV Forum of Sociology (International Sociological Association), Porto Alegre (online). \hfill \begingroup\small 2021\endgroup

Day of Sociology, Amsterdam. \hfill \begingroup\small 2019\endgroup

# Professional Activities
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

## Academic Service
Presider roundtable cultural sociology (section on Meritocracy) at 116th ASA Virtual Annual Meeting.
Chair session on Class and Status at 21st IASPM Annual Meeting.

## Occasional Reviewer
Journal for the Theory of Social Behaviour

## Memberships & Affiliations
International Association for the Study of Popular Music (IASPM). \hfill \begingroup\small 2022-present\endgroup

International Communication Association (ICA). \hfill \begingroup\small 2022-present\endgroup

Netherlands – Flanders Communication Association (NeFCA). \hfill \begingroup\small 2020-present\endgroup

American Sociological Association (ASA). \hfill \begingroup\small 2021-present\endgroup

KU Leuven Digital Society Institute. \hfill \begingroup\small 2021-present\endgroup

KU Leuven Youth Institute. \hfill \begingroup\small 2021-present\endgroup

## Research stays
Research stay hosted by Prof. Michèle Lamont at Harvard University. \hfill \begingroup\small Spring 2024\endgroup

Research stay hosted by Prof. Hyunjin Song at Yonsei University. \hfill \begingroup\small July 2022\endgroup

Research stay hosted by Prof. Eric Lybeck at Exeter University. \hfill \begingroup\small June-August 2018\endgroup

## Faculty Services
*Co-Director* of MethLab\hfill \begingroup\small September 2020-present\endgroup\
*[Meth-Lab](https://soc.kuleuven.be/fsw/doctoralprogramme/meth-lab) is a bottom-up initiative created by Lala Muradova and Amélie Godefroidt at KU Leuven for the sharing and presentation of novel methodological techniques. As a co-director, I am responsible for contacting and welcoming national and international speakers, the organization of the meetings, the promotion of the events, and the management of finances.*

*Member* of Diversity and Sustainability Commission at KU Leuven (FSW)\hfill \begingroup\small April 2021- present\endgroup\

*Supervisor* MA thesis students:\newline
- Hong Zhan\hfill \begingroup\small 2021\endgroup\
- Sarah Pans\hfill \begingroup\small 2022\endgroup\
- Kyra Bulinckx\hfill \begingroup\small 2022\endgroup\
- Diana-Teodora Gaitan\hfill \begingroup\small 2022\endgroup\
- Dan Ding\hfill \begingroup\small 2022\endgroup\
- Maria Stefania Popa\hfill \begingroup\small 2022\endgroup\
- Ngoc Diep Nguyen\hfill \begingroup\small 2022\endgroup\

*Supervisor* job students:\newline
- Rana Rafeh\hfill \begingroup\small 2022\endgroup\
- Tam Nguyen\hfill \begingroup\small 2022\endgroup\
- Silke Vereeken\hfill \begingroup\small 2021\endgroup\
- Annelies Rom\hfill \begingroup\small 2021\endgroup\

# Research Experience
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

Department of Sociology, Tilburg University \hfill \begingroup\small March 2019 – September 2019\endgroup\
Research assistant, Supervisor: Prof. dr. Ruud Muffels\
*Research on basic income in the Netherlands.*

Research Institute Carlo Cattaneo, Bologna \hfill \begingroup\small January 2019 – June 2019\endgroup\
Research collaborator\
*Political discourses on Twitter.*

Research Institute IRVAPP, Trento \hfill \begingroup\small February 2017 – May 2017\endgroup\
Research internship, Supervisor: Dr. Sonia Marzadro\
*Evaluation of social policies for the European project Youth Guarantee.*

# Teaching Experience
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

School for Mass Communication Research, KU Leuven \hfill \begingroup\small October 2021 – present\endgroup\
Teaching assistant\
*Course: Research Designs for Communication Science. Seminar name: Computational methods for text analysis*

School for Mass Communication Research, KU Leuven \hfill \begingroup\small November 2021 – present\endgroup\
Teaching assistant\
*Course: Media and Crisis. Seminar name: Social media: a curse or blessing for the body image crisis?*
*Course: Media and Crisis. Seminar name: Music and the cracks of individualism(?)*

Department of Sociology, Tilburg University \hfill \begingroup\small March 2017 – June 2017\endgroup\
Teaching assistant\
*Course: Social Risk and Culture*

Department of Methodology & Statistics, Tilburg University \hfill \begingroup\small February 2017 – June 2017\endgroup\
Teaching assistant\
*Courses: Introduction to Statistics, Questionnaire design, Experimental design*

# Software
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}
`chorrrds`: Music chords extraction - Collaborator\
*Available at: https://CRAN.R-project.org/package=chorrrds*

# Skills
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

## Programming Languages & Softwares
R (Advanced)\
Markdown (Intermediate)\
Python (Intermediate)\
Mplus (Basic)\
HTML (Basic)\
CSS (Basic)
\newline

## Languages
Italian (Native speaker)\
English (Full professional proficiency)\
French (Intermediate proficiency)
Spanish (Elementary proficiency)\
\newline

## Additional training
Summer School Diversity in Arts, Culture and Media Studies, Erasmus University Rotterdam \hfill \begingroup\small June, 2022\endgroup\
*Critical, feminist, and intersectional approaches*

Essex Summer School in Social Science Data Analysis, Essex University \hfill \begingroup\small August, 2020\endgroup\
*Mathematics*, *Quantitative text analysis*

MOOC on “Introduction to Agent-Based Modeling”, Santa Fe Institute \hfill \begingroup\small October, 2019\endgroup\
*Agent-based modelling on NetLogo*

MOOC on “Social and Economic Networks: Models and Analysis”, \hfill \begingroup\small August, 2019\endgroup\
Stanford University\
*Social network analysis*

Summer School at CWST Center, Leiden University \hfill \begingroup\small August, 2018\endgroup\
*Scientometrics analysis*

Seminar on The Path to Quantitative Research, University of Trento \hfill \begingroup\small 2016\endgroup\
*Factor analysis and counterfactual techniques for impact evaluation*
\newline

## Social causes
Volunteering for Cultuur en Ontspanningscentrum \hfill \begingroup\small April 2019 – June 2019\endgroup\
*The mission is to integrate sexual orientations, gender identities, gender expression, and sex characteristics of sexual and gender minority groups into the social norm through social activism, education, support, and representation.*

Volunteering for “L’Universitario” \hfill \begingroup\small September 2016 – June 2017\endgroup\
*Founder of this university newspaper and director section “Scientific Divulgation”.*

Volunteering for Arci \hfill \begingroup\small June 2014 – July 2014\endgroup\
*Requalification of terrains confiscated to mafia with the project “Campi della Legalità”.*

# References
\vspace{-10pt}
\rule{1\linewidth}{\linethickness}

Available under request.