import { SectionAlternative, SectionContent } from "../site/SectionContent";
import { Vnode } from "mithril";
import { Section } from "../site/Section";
export declare class Content extends SectionContent {
    private readonly userIdList;
    private readonly studyId;
    private userId;
    private readonly fixedRecipient;
    private messages?;
    private sortedMessages;
    private toAll;
    private appVersion;
    private appType;
    private messageContent;
    private isLoading;
    static preLoad(section: Section): Promise<any>[];
    constructor(section: Section, userIdList: string[]);
    preInit(): Promise<any>;
    title(): string;
    titleExtra(): Vnode<any, any> | null;
    hasAlternatives(): boolean;
    getAlternatives(): Promise<SectionAlternative[]>;
    private loadParticipantMessages;
    private getUnreadTimestamps;
    private removeMessage;
    private sendMessage;
    private setMessagesAsRead;
    getView(): Vnode<any, any>;
    private getBubble;
}
