import { SectionContent } from "../site/SectionContent";
import { Vnode } from "mithril";
import { Section } from "../site/Section";
import { CsvLoader } from "../loader/csv/CsvLoader";
export declare class Content extends SectionContent {
    private csvLoader;
    private readonly enableGroupStatistics;
    private days;
    private questionnairesTotalCount;
    private joinedTotalCount;
    private quitTotalCount;
    private modelsList;
    private readonly appTypeChart;
    private readonly questionnairesChart?;
    private readonly joinedPerDayChart;
    private readonly groupJoinedChart?;
    private readonly quitPerDayChart;
    private readonly groupQuitChart?;
    private readonly questionnairePerDayChart;
    private readonly groupQuestionnairePerDayChart;
    private readonly appVersionPerDayChart;
    private readonly studyVersionPerDayChart;
    private readonly appTypePromise;
    private readonly questionnairesPromise;
    private readonly questionnairePerDayPromise;
    private readonly joinedPerDayPromise;
    private readonly groupJoinedPromise;
    private readonly quitPerDayPromise;
    private readonly groupQuitPromise;
    private readonly appVersionPerDayPromise;
    private readonly studyVersionPerDayPromise;
    static preLoad(section: Section): Promise<any>[];
    constructor(section: Section, csvLoader: CsvLoader);
    preInit(): Promise<void>;
    title(): string;
    titleExtra(): Vnode<any, any> | null;
    private getDayChartAxisContainerCode;
    private createPerDayChartData;
    private createSumChartData;
    private updateCharts;
    private createFixedStatistics;
    private reloadDynamicStatistics;
    getView(): Vnode<any, any>;
}
