import { SectionContent } from "../site/SectionContent";
import { Vnode } from "mithril";
import { Section } from "../site/Section";
import { CsvLoader } from "../loader/csv/CsvLoader";
import { Study } from "../data/study/Study";
export declare class Content extends SectionContent {
    private readonly csvLoader;
    private readonly personalStatisticsCsvLoaderCollection;
    private readonly enableGroupStatistics;
    private publicStatistics?;
    private participantList;
    private groupList;
    private timezoneList;
    private appTypeList;
    private modelList;
    private joinedTimeList;
    private quitTimeList;
    private currentParticipant;
    private isLoading;
    private readonly joinedPerDayChart;
    private readonly joinedPerDayPromise;
    private readonly personalChartPromises;
    static preLoad(section: Section): Promise<any>[];
    constructor(section: Section, csvLoader: CsvLoader, study: Study);
    preInit(): Promise<void>;
    title(): string;
    titleExtra(): Vnode<any, any> | null;
    private loadParticipants;
    private selectParticipant;
    getView(): Vnode<any, any>;
    private getListEntryView;
}
